### ISSUE TITLE
Update a person in Customer.io when the "Set" function is called  

### ISSUE THREAD

**Issue by davidgreyme** [PostHog/customerio-plugin#12]
Currently there's no way to update a person's info once it's created in Customer.io. In PostHog, we use the "Set" function to update a user's info so it would make sense to have the "Set" function send an update request to Customer.io.

One use case is if we have a multi-step signup form, currently there's no way fill the person's info after every step. We call Identify after the first step which includes the user's unique id and email, but then when we ask for the user's first name, interests, etc in the next steps, this info doesn't reach Customer.io.  Calling identify again after every step doesn't work either.

**Comment by Twixes** [comment]
This should be fixed now! The `$set` object is now used to update customers.
