### ISSUE TITLE
Created at is sent in invalid format. 

### ISSUE THREAD

**Issue by jamesblackwell** [PostHog/customerio-plugin#27]
Customer.io requires unix time e.g. `1687336824` 

Posthog is currently sending an invalid format e.g. `2023-06-15T05:40:43.000000Z`, causing errors in customer.io. 

Until fixed, the plugin is not really usable.

**Comment by altechzilla** [comment]
Is this plugin still maintained at all?

**Comment by tiina303** [comment]
Looks like this was fixed already in https://github.com/PostHog/customerio-plugin/pull/28 I've just updated the app in our US cloud instances.
